language: perl6
perl6:
    - latest

install:
    - rakudobrew build-zef
    - zef update
    - zef --force --depsonly install .
script:
    - git submodule update --init --recursive
    - perl6 ./UCD-download.p6
    - prove -e perl6
    - perl6 ./UCD-gen.p6
    - make
